include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-systembus-cpu
PKG_VERSION:=0.91
PKG_RELEASE:=3
PKG_MAINTAINER:=Oskari Rauta <oskari.rauta@gmail.com>

LUCI_TITLE:=Systembus cpu statistics
LUCI_DEPENDS:=+luci-mod-status +systembus
LUCI_PKGARCH:=all

include ../../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
