include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-status-extended
PKG_VERSION:=1.0
PKG_RELEASE:=1
PKG_MAINTAINER:=Oskari Rauta <oskari.rauta@gmail.com>

LUCI_TITLE:=Extended system status view for LuCI
LUCI_DEPENDS:=+luci-mod-status
LUCI_PKGARCH:=all

include ../../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
