include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for CNI protocol
LUCI_DEPENDS:=+cni-protocol

PKG_MAINTAINER:=Oskari Rauta <oskari.rauta@gmail.com>

include ../../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
