obj-m += mpro.o
mpro-y := mpro_drv.o mpro_io.o mpro_touch.o mpro_model.o mpro_bl.o mpro_connector.o mpro_pipe.o mpro_sysfs.o mpro_flip.o
ifeq ($(MAKING_MODULES),1)
-include $(TOPDIR)/Rules.make
endif
