include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Zerotier
LUCI_DEPENDS:=+zerotier

PKG_MAINTAINER:=Oskari Rauta <oskari.rauta@gmail.com>

include ../../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
